#!/usr/bin/env bash
# search subdomain for an IP
func_web_info ()
{
    if [ $2 ]; then
	dig $2.$1 | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk -v name=$2 '{print "The subdomain", name, "is a", $4, "record and points to", $5}'
    else
	dig "www".$1 | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain www is a", $4, "record and points to", $5}'
	dig "lb-01".$1 | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain lb-01 is a", $4, "record and points to", $5}'
	dig "web-01".$1 | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain web-01 is a", $4, "record and points to", $5}'
	dig "web-02".$1 | awk 'f;/ANSWER SECTION:/{f=1}' | head -n 1 | awk '{print "The subdomain web-02 is a", $4, "record and points to", $5}'
    fi
}
func_web_info "$1" "$2"
