#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sed -i ''