#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install -y Haproxy
# create copy configuration files for errors
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg_copy
sudo cp /etc/default/haproxy /etc/default/haproxy.copy
# configure file haproxy.cfg with frontend and backend
sudo echo -e "\\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver gc-1888-web-01-1607372328 104.196.132.76:80 check\n\tserver gc-1888-web-02-1608528167 35.243.198.29:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
