#!/usr/bin/env bash
# print 10 times holb Sch... and good/bad look
i=0
while [ $i -lt 10 ]
do
	i=$((i + 1))
	if [ $i == 8 ]
		then
			echo "good luck"
			continue
	elif [ $i == 4 ]
		then
			echo "bad luck"
			continue
	else
		echo "Holberton School"
	fi
done
