#!/usr/bin/env bash
# print 10 times holb Sch... and good/bad look
i=1
while [ $i -lt 11 ]
do
	i=$((i + 1))
	if [ $i == 9 ]
		then
			echo "good luck"
			continue
	elif [ $i == 5 ]
		then
			echo "back luck"
			continue
	else
		echo "Holberton School"
	fi
done
