#!/usr/bin/env bash
# print conditions for files
if [ -e "holbertonschool" ]
then
    echo "holbertonschool file exists"
    if [ ! -s "holbertonschool" ]
    then
        echo "holbertonschool file is empty"
    else
        echo "holbertonschool file is not empty"
    fi
    if [ -f "holbertonschool" ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
