#!/usr/bin/env bash
# configures an ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i s/"127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
